### ISSUE TITLE
add body class functionality

### ISSUE THREAD

**Issue by whatnickcodes** [scotch-io/stencil#2]
``` php
$this->data['body_class'] = $this->CI->router->fetch_class().' '.$this->CI->router->fetch_class().'-'.$this->CI->router->fetch_method();
```

Add this to paint() function in libary/Stencil.php

Note: This makes $body_class now a reserved variable name in views

**Comment by whatnickcodes** [comment]
## NOTE:

``` php
<?php

class Example extends CI_Controller {

     function index() {
          $this->stencil->paint('example_view');
     }

}
```

/example and /example/index will yield this:

``` html
<body class="example example-index">
```

But this "/example/8349023849023849032" will yield this:

``` html
<body class="example example-8349023849023849032">
```

#### example-index won't exist

Obviously -- 8349023849023849032 is not a function name, but a URI segment just appended to the URL. So it should be noted somewhere in the docs that this isn't _technically_ a bullet proof method

**Comment by chris-sev** [comment]
When it does a 404 error, the body class is "pages pages-index".

How do you want to fix that? We could have 404 be its own controller or method.
